<?php

/**
 * @file
 * define hooks and menu
 */

/**
 * Implement hook_form_islandora_object_properties_form_alter().
 */

function islandora_elide_download_form_islandora_object_properties_form_alter(array &$form, array &$form_state) {
  module_load_include('inc', 'islandora_elide_download', 'includes/utilities');
  $form['toggle_elide_dl'] = array(
    '#type' => 'checkbox',
    '#title' => t('Hide Download Link'),
    '#description' => t('Check this box to hide download link from user'),
    '#default_value' => islandora_elide_download_is_listed($form['pid']['#value']),
  );
    array_unshift($form['#submit'], 'islandora_elide_download_submit_handler');
}

/**
 * Implement hook_islandora_object_ingested().
 * //works like a charm with one item and works with gui batch ingest
 */

function islandora_elide_download_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_elide_download', 'includes/utilities');
  islandora_elide_download_toggle_elide_link($object->id);
  //$object set to either 'enabled' or 'elide' on ingest
  //dpm('ingested: ' . $object->label );
}


//find islandora_importer/zip_importer form and add option to elide links for all, or enable link for all.
