<?php

/**
 * @file
 * define hooks and menu
 */

/**
 * Implement hook_form_islandora_object_properties_form_alter().
 */
function islandora_elide_download_form_islandora_object_properties_form_alter(array &$form, array &$form_state) {
  module_load_include('inc', 'islandora_elide_download', 'includes/utilities');
  $form['toggle_elide_dl'] = array(
    '#type' => 'checkbox',
    '#title' => t('Hide Download Link'),
    '#description' => t('Check this box to hide download link from user'),
    '#default_value' => islandora_elide_download_is_listed($form['pid']['#value']),
  );
    array_unshift($form['#submit'], 'islandora_elide_download_submit_handler');
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function islandora_elide_download_form_islandora_ingest_form_alter(&$form, &$form_state) {
  //debug($form);
  $form['#submit'] = 'islandora_elide_download_callback';

}

/**
 * Callback function to elide or enable the download
 */
function islandora_elide_download_callback(&$form, &$form_state) {
    drupal_set_message('goddamit');
  module_load_include('inc', 'islandora_elide_download', 'includes/utilities');
  $fn = 'islandora_elide_download_toggle_link';
  $arg = $form_state['toggle_elide_dl'] ? 'elide': 'enable';
  $pid = $form_state['islandora']['objectid'];
  $fn($arg,$pid);
}

/**
 * hook_process_islandora_large_image(). //will need to implement for each cmodel...
 * Deletes 'downloads' div if the object is listed in the db
 */
function islandora_elide_download_process_islandora_large_image(&$variables) {
  $pid = $variables['islandora_object']->id;
  module_load_include('inc', 'islandora_elide_download', 'includes/utilities');
  if(islandora_elide_download_is_listed($pid)){
    $variables['downloads'] = [];
  }
}
